// Emits MoveAnimData.g.cs: per-move keyframe tables. Moves with extracted Showdown keyframes use
// them verbatim (as data); the rest get a synthesized default built from their pattern + fx sprite,
// so every move plays through the same tween runtime with real sprites.
const fs = require('fs');
const path = require('path');
const { moves: kf } = require('./keyframes.json');
const { visuals } = require('./movevisuals.json');
const dims = require('./fx_dims.json');
const { moves } = require('./gen1.json');

const f = (n) => {
  const r = Math.round(n * 1000) / 1000;
  return (Number.isInteger(r) ? r + '' : r + '') + 'f';
};
const csStr = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
const B = { a: 'A', d: 'D', m: 'M', k: 'K' };
const EASE = {
  linear: 'Linear', accel: 'Accel', decel: 'Decel', swing: 'Swing', ballistic: 'Ballistic',
  ballisticUp: 'BallisticUp', ballisticDown: 'BallisticDown', ballistic2: 'Ballistic',
  ballistic2Back: 'Ballistic', ballistic2Under: 'Ballistic', quadUp: 'Accel', quadDown: 'Decel',
};
const ease = (t) => EASE[t] || 'Linear';

function coord(c) { return `${B[c.b] || 'D'}(${f(c.off)})`; }
function st(s) {
  return `St(${coord(s.x)}, ${coord(s.y)}, ${coord(s.z)}, ${f(s.scale)}, ${f(s.opacity)}, ${f(s.time)})`;
}
function fxLine(fx) {
  const d = dims[fx.sprite] || [40, 40];
  return `Fx(${csStr(fx.sprite)}, ${d[0]}, ${d[1]}, ${st(fx.s)}, ${st(fx.e)}, ${ease(fx.t)})`;
}
function bgLine(b) {
  const hex = (b.color || '#000000').replace('#', '');
  const rgb = parseInt(hex.length === 3 ? hex.split('').map((c) => c + c).join('') : hex, 16) || 0;
  return `Bg(0x${rgb.toString(16).padStart(6, '0').toUpperCase()}, ${f(b.op)}, ${f(b.time)}, ${f(b.dur)})`;
}

// --- Synthesize a default animation for moves without extracted keyframes. ---
const C = (b, off) => ({ b, off });
const S = (x, y, z, scale, opacity, time) => ({ x, y, z, scale, opacity, time });
function synth(pattern, sprite) {
  const P = sprite;
  switch (pattern) {
    case 'Beam':
      return { dur: 460, fx: [
        { sprite: P, t: 'accel', s: S(C('a', 0), C('a', 0), C('a', 0), 0.7, 0.9, 0), e: S(C('d', 0), C('d', 0), C('d', 0), 1.3, 1, 220) },
        { sprite: P, t: 'decel', s: S(C('d', 0), C('d', 0), C('d', 0), 1.3, 1, 200), e: S(C('d', 0), C('d', 20), C('d', 0), 2.4, 0, 460) },
      ], bg: [] };
    case 'Contact':
      return { dur: 440, fx: [
        { sprite: P, t: 'decel', s: S(C('d', 0), C('d', 0), C('d', 0), 0.4, 1, 170), e: S(C('d', 0), C('d', 15), C('d', 0), 2.6, 0, 440) },
      ], bg: [] };
    case 'SelfBuff':
      return { dur: 620, fx: [
        { sprite: P, t: 'decel', s: S(C('a', -22), C('a', -20), C('a', 0), 0.7, 1, 0), e: S(C('a', -22), C('a', 50), C('a', 0), 1, 0, 380) },
        { sprite: P, t: 'decel', s: S(C('a', 22), C('a', -20), C('a', 0), 0.7, 1, 130), e: S(C('a', 22), C('a', 50), C('a', 0), 1, 0, 500) },
        { sprite: P, t: 'decel', s: S(C('a', 0), C('a', -26), C('a', 0), 0.8, 1, 250), e: S(C('a', 0), C('a', 55), C('a', 0), 1.1, 0, 620) },
      ], bg: [] };
    case 'Cloud':
      return { dur: 560, fx: [0, 1, 2, 3].map((i) => ({
        sprite: P, t: 'decel',
        s: S(C('d', (i - 1.5) * 16), C('d', 10 + (i % 2) * 14), C('d', 0), 0.4, 1, i * 90),
        e: S(C('d', (i - 1.5) * 22), C('d', 40 + (i % 2) * 14), C('d', 0), 1.3, 0, i * 90 + 340),
      })), bg: [] };
    default: // Projectile
      return { dur: 470, fx: [
        { sprite: P, t: 'linear', s: S(C('a', 0), C('a', 0), C('a', 0), 1, 1, 0), e: S(C('d', 0), C('d', 0), C('d', 0), 1.1, 1, 300) },
        { sprite: P, t: 'decel', s: S(C('d', 0), C('d', 0), C('d', 0), 0.7, 1, 290), e: S(C('d', 0), C('d', 25), C('d', 0), 2.6, 0, 470) },
      ], bg: [] };
  }
}

const L = [];
L.push('// <auto-generated> Move-animation keyframes ported from Pokémon Showdown (CC0 BattleMoveAnims).');
L.push('#nullable enable');
L.push('namespace VideoSyncPrototype.Phone.Apps.LillypadGo;');
L.push('');
L.push('internal static partial class MoveAnims');
L.push('{');
L.push('    static partial void Populate()');
L.push('    {');
let exact = 0, synthesized = 0;
for (const mv of moves) {
  let data = kf[mv.name];
  if (data && data.fx && data.fx.length) {
    exact++;
  } else {
    const v = visuals[mv.name] || { pattern: 'Projectile', sprite: 'wisp' };
    data = synth(v.pattern, v.sprite);
    synthesized++;
  }
  const fxArr = data.fx.map(fxLine).join(',\n            ');
  const bgArr = (data.bg || []).map(bgLine).join(', ');
  L.push(`        Add(${csStr(mv.name)}, ${f(Math.min(data.dur, 1300))},`);
  L.push(`            new[] { ${fxArr} },`);
  L.push(`            new AnimBg[] { ${bgArr} });`);
}
L.push('    }');
L.push('}');
fs.writeFileSync(path.join(__dirname, 'out', 'MoveAnimData.g.cs'), L.join('\n') + '\n');
console.log('emitted MoveAnimData.g.cs:', moves.length, 'moves; exact=' + exact, 'synthesized=' + synthesized);
