// Emits C# source from gen1.json: Moves registry, Dex (151 species), and
// Kanto-flavoured Biome/Zone encounter tables.
const fs = require('fs');
const path = require('path');
const { species, moves } = require('./gen1.json');
const OUT = path.join(__dirname, 'out');
fs.mkdirSync(OUT, { recursive: true });

const f = (n) => (Math.round(n * 100) / 100).toString() + 'f';
const vec = (c) => `new Vector4(${f(c[0])}, ${f(c[1])}, ${f(c[2])}, 1f)`;
const darken = (c, k) => c.map((v) => v * k);
const lighten = (c, k) => c.map((v) => v + (1 - v) * k);
const csStr = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';

// ---------- Moves ----------
function emitMoves() {
  const L = [];
  L.push('// <auto-generated> Gen-1 move data ported from Pokémon Showdown (data/moves.ts).');
  L.push('#nullable enable');
  L.push('namespace VideoSyncPrototype.Phone.Apps.LillypadGo;');
  L.push('');
  L.push('// The move pool. Ids match Showdown move ids; species learnsets reference them via Moves.M(id).');
  L.push('internal static class Moves');
  L.push('{');
  L.push('    private static readonly Dictionary<string, MoveDef> ById = Build();');
  L.push('');
  L.push('    private static Dictionary<string, MoveDef> Build()');
  L.push('    {');
  L.push('        var d = new Dictionary<string, MoveDef>(StringComparer.OrdinalIgnoreCase);');
  for (const m of moves) {
    const cat = m.category === 'Special' ? 'Special' : m.category === 'Status' ? 'Status' : 'Physical';
    L.push(`        d[${csStr(m.id)}] = new MoveDef(${csStr(m.name)}, Element.${m.type}, ${m.power}, ${m.accuracy}, ${m.pp}, MoveEffect.${m.effect}, ${m.chance}, MoveCategory.${cat}, ${m.priority}, ${m.stage});`);
  }
  L.push('        return d;');
  L.push('    }');
  L.push('');
  L.push('    public static readonly MoveDef Tackle = ById["tackle"];');
  L.push('    public static readonly MoveDef Struggle = ById["struggle"];');
  L.push('');
  L.push('    // Name -> def, for resolving persisted saves (which store display names).');
  L.push('    private static readonly Dictionary<string, MoveDef> ByName =');
  L.push('        ById.Values.Distinct().ToDictionary(m => m.Name, m => m, StringComparer.OrdinalIgnoreCase);');
  L.push('');
  L.push('    public static MoveDef M(string id) => ById[id];');
  L.push('    public static MoveDef? Find(string name) =>');
  L.push('        ByName.TryGetValue(name, out var move) ? move : ById.TryGetValue(name, out var byId) ? byId : null;');
  L.push('    public static IReadOnlyCollection<MoveDef> All => ByName.Values;');
  L.push('}');
  fs.writeFileSync(path.join(OUT, 'MovesData.g.cs'), L.join('\n') + '\n');
}

// ---------- Art silhouette (procedural fallback only) ----------
const COLOR = {
  Red: [0.85, 0.28, 0.24], Blue: [0.30, 0.48, 0.86], Yellow: [0.95, 0.80, 0.28],
  Green: [0.42, 0.72, 0.36], Black: [0.30, 0.30, 0.34], Brown: [0.60, 0.44, 0.28],
  Purple: [0.58, 0.40, 0.70], Gray: [0.62, 0.64, 0.66], White: [0.90, 0.92, 0.95],
  Pink: [0.94, 0.62, 0.72],
};
function artSpec(s) {
  const t = s.types;
  const has = (x) => t.includes(x);
  let shape = 'Quadruped';
  if (has('Flying')) shape = 'Avian';
  else if (has('Bug')) shape = 'Insectoid';
  else if (has('Ghost') || (has('Psychic') && !has('Fighting'))) shape = 'Wisp';
  else if (has('Dragon') || (has('Poison') && s.bst < 340)) shape = 'Serpent';
  else if (has('Water') && !has('Ground')) shape = 'Blob';
  const primary = COLOR[s.color] || [0.6, 0.6, 0.62];
  const secondary = darken(primary, 0.62);
  const belly = lighten(primary, 0.5);
  const eye = [0.16, 0.16, 0.22];
  const flags = [];
  if (has('Rock') || has('Ground') || has('Dragon')) flags.push('horns: true');
  if (has('Flying') || has('Bug')) flags.push('wings: true');
  if (shape !== 'Blob' && shape !== 'Wisp') flags.push('tail: true');
  if (has('Rock') || has('Steel') || has('Ground')) flags.push('spikes: true');
  if (has('Water')) flags.push('fins: true');
  const flagStr = flags.length ? ', ' + flags.join(', ') : '';
  return `new ArtSpec(Archetype.${shape}, ${vec(primary)}, ${vec(secondary)}, ${vec(belly)}, ${vec(eye)}${flagStr})`;
}

// ---------- Dex ----------
function emitDex() {
  const L = [];
  L.push('// <auto-generated> Gen-1 (#1-151) species ported from Pokémon Showdown (data/pokedex.ts).');
  L.push('using System.Numerics;');
  L.push('');
  L.push('namespace VideoSyncPrototype.Phone.Apps.LillypadGo;');
  L.push('');
  L.push('internal static partial class Dex');
  L.push('{');
  L.push('    static partial void Populate()');
  L.push('    {');
  for (const s of species) {
    const type2 = s.types[1] ? `Element.${s.types[1]}` : 'null';
    const st = s.stats;
    const ls = s.learnset.map((e) => `(${e.level}, ${csStr(e.moveid)})`).join(', ');
    const evoTo = s.evo ? csStr(s.evo.toId) : 'null';
    const evoLevel = s.evo ? (s.evo.level || 0) : 0;
    const evoMethod = s.evo && s.evo.method ? csStr(s.evo.method) : 'null';
    L.push(`        Add(${csStr(s.id)}, ${csStr(s.name)}, Element.${s.types[0]}, ${type2}, ${st.hp}, ${st.atk}, ${st.def}, ${st.spa}, ${st.spd}, ${st.spe}, ${s.capture}, ${s.num},`);
    L.push(`            ${artSpec(s)},`);
    L.push(`            new (int, string)[] { ${ls} }, ${evoTo}, ${evoLevel}, ${evoMethod});`);
  }
  L.push('    }');
  L.push('}');
  fs.writeFileSync(path.join(OUT, 'PokedexData.g.cs'), L.join('\n') + '\n');
}

// ---------- Biome / Zone encounter tables ----------
const TYPE_BIOMES = {
  Fire: ['Volcanic', 'Desert'], Water: ['Coast', 'Wetland'], Grass: ['Forest', 'Grassland'],
  Bug: ['Forest', 'Grassland'], Ice: ['Snow'], Electric: ['Grassland', 'Coast'],
  Ground: ['Desert', 'Cave'], Rock: ['Cave', 'Desert'], Flying: ['Grassland', 'Coast'],
  Poison: ['Wetland', 'Cave'], Psychic: ['Grassland', 'Cave'], Ghost: ['Cave'],
  Dragon: ['Cave', 'Volcanic'], Fighting: ['Cave', 'Grassland'], Normal: ['Grassland', 'Forest'],
  Fairy: ['Grassland'], Steel: ['Cave'],
};
const BIOMES = ['Forest', 'Grassland', 'Desert', 'Coast', 'Snow', 'Volcanic', 'Cave', 'Wetland'];

function biomesOf(s) {
  const set = new Set();
  for (const t of s.types) for (const b of (TYPE_BIOMES[t] || [])) set.add(b);
  if (set.size === 0) set.add('Grassland');
  return [...set];
}

// members[biome] = [{id,name,bst,legendary,cap}]
const members = Object.fromEntries(BIOMES.map((b) => [b, []]));
for (const s of species) {
  for (const b of biomesOf(s)) members[b].push({ id: s.id, bst: s.bst, legendary: s.legendary });
}
for (const b of BIOMES) members[b].sort((a, c) => a.bst - c.bst);

function pickNear(pool, targetBst, count, allowLegend) {
  const cand = pool.filter((m) => allowLegend || !m.legendary)
    .slice().sort((a, c) => Math.abs(a.bst - targetBst) - Math.abs(c.bst - targetBst));
  const out = [];
  for (const m of cand) { if (!out.find((o) => o.id === m.id)) out.push(m); if (out.length >= count) break; }
  return out;
}

function emitBiome() {
  // Overworld fallback spawns: weakest few per biome, low levels.
  const lines = [];
  for (const b of BIOMES) {
    const picks = pickNear(members[b], 260, 4, false);
    const entries = picks.map((m, i) => `new SpawnEntry("${m.id}", ${40 - i * 8}, 2, ${6 + i})`).join(', ');
    lines.push(`        [Biome.${b}] = new[]\n        {\n            ${entries},\n        },`);
  }
  const src = fs.readFileSync(path.join(__dirname, 'tpl', 'Biome.cs.tpl'), 'utf8');
  fs.writeFileSync(path.join(OUT, 'Biome.cs'), src.replace('/*__TABLES__*/', lines.join('\n')));
}

// Zone scaffolds preserved from the original ArrZones (territory/region/order/name/biome/level bands).
const ZONES = [
  [134, 'La Noscea', 0, 'Middle La Noscea', 'Coast', 0, 2, 8],
  [148, 'The Black Shroud', 1, 'Central Shroud', 'Forest', 1, 2, 8],
  [141, 'Thanalan', 2, 'Central Thanalan', 'Desert', 2, 2, 8],
  [135, 'La Noscea', 0, 'Lower La Noscea', 'Coast', 3, 5, 12],
  [140, 'Thanalan', 2, 'Western Thanalan', 'Desert', 4, 6, 14],
  [152, 'The Black Shroud', 1, 'East Shroud', 'Forest', 5, 8, 16],
  [138, 'La Noscea', 0, 'Western La Noscea', 'Coast', 6, 10, 18],
  [145, 'Thanalan', 2, 'Eastern Thanalan', 'Desert', 7, 12, 22],
  [153, 'The Black Shroud', 1, 'South Shroud', 'Wetland', 8, 18, 28],
  [139, 'La Noscea', 0, 'Upper La Noscea', 'Wetland', 9, 20, 30],
  [154, 'The Black Shroud', 1, 'North Shroud', 'Forest', 10, 24, 34],
  [146, 'Thanalan', 2, 'Southern Thanalan', 'Desert', 11, 25, 38],
  [137, 'La Noscea', 0, 'Eastern La Noscea', 'Coast', 12, 28, 38],
  [180, 'La Noscea', 0, 'Outer La Noscea', 'Volcanic', 13, 34, 43],
  [147, 'Thanalan', 2, 'Northern Thanalan', 'Volcanic', 14, 38, 46],
  [155, 'Coerthas', 3, 'Coerthas Central Highlands', 'Snow', 15, 40, 48],
  [156, 'Mor Dhona', 4, 'Mor Dhona', 'Wetland', 16, 44, 50],
];

function emitZones() {
  const maxProg = ZONES.length - 1;
  const lines = [];
  for (const [terr, region, ro, name, biome, prog, min, max] of ZONES) {
    const t = prog / maxProg;
    const targetBst = Math.round(250 + t * 350);
    const allowLegend = prog >= maxProg - 2;
    const picks = pickNear(members[biome], targetBst, 5, allowLegend);
    // exclusive = the strongest fitting member; rest are the encounter list
    const exclusive = picks[picks.length - 1];
    const enc = picks.slice(0, 4);
    const entries = enc.map((m, i) => {
      const w = m.id === exclusive.id ? (m.legendary ? 6 : 22) : 34 - i * 6;
      return `new SpawnEntry("${m.id}", ${w}, ${min}, ${max})`;
    });
    // ensure exclusive appears in the encounter list
    if (!enc.find((m) => m.id === exclusive.id)) {
      entries.push(`new SpawnEntry("${exclusive.id}", ${exclusive.legendary ? 6 : 22}, ${min}, ${max})`);
    }
    lines.push(`        new ZoneDefinition(${terr}, "${region}", ${ro}, "${name}", Biome.${biome}, ${prog}, ${min}, ${max}, "${exclusive.id}",\n            ${entries.join(', ')}),`);
  }
  const src = fs.readFileSync(path.join(__dirname, 'tpl', 'ZoneCatalog.cs.tpl'), 'utf8');
  fs.writeFileSync(path.join(OUT, 'ZoneCatalog.cs'), src.replace('/*__ZONES__*/', lines.join('\n')));

  // summary
  console.log('Zone encounters:');
  for (const [, , , name, biome, prog, min, max] of ZONES) {
    const t = prog / maxProg, targetBst = Math.round(250 + t * 350);
    const allowLegend = prog >= maxProg - 2;
    const picks = pickNear(members[biome], targetBst, 5, allowLegend);
    console.log(`  ${name} (${biome} Lv${min}-${max}) -> ` + picks.map((m) => m.id).join(', '));
  }
}

emitMoves();
emitDex();
emitBiome();
emitZones();
console.log('\nEmitted to out/. moves=%d species=%d', moves.length, species.length);
