// Emits MoveVisuals.g.cs: move display-name -> { pattern, fx sprite name }.
const fs = require('fs');
const path = require('path');
const { visuals } = require('./movevisuals.json');
const csStr = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';

const L = [];
L.push('// <auto-generated> Per-move animation mapping derived from Pokémon Showdown (CC0 BattleMoveAnims).');
L.push('#nullable enable');
L.push('namespace VideoSyncPrototype.Phone.Apps.LillypadGo;');
L.push('');
L.push('internal enum MoveFxPattern : byte { Projectile, Beam, Contact, SelfBuff, Cloud }');
L.push('');
L.push('// Which fx sprite a move throws and how it moves. Sprite art is bundled in Assets/pokemon/fx.');
L.push('internal readonly struct MoveVisual');
L.push('{');
L.push('    public MoveVisual(MoveFxPattern pattern, string sprite)');
L.push('    {');
L.push('        Pattern = pattern;');
L.push('        Sprite = sprite;');
L.push('    }');
L.push('');
L.push('    public MoveFxPattern Pattern { get; }');
L.push('    public string Sprite { get; }');
L.push('}');
L.push('');
L.push('internal static class MoveVisuals');
L.push('{');
L.push('    private static readonly Dictionary<string, MoveVisual> ByName = new(StringComparer.OrdinalIgnoreCase)');
L.push('    {');
for (const [name, v] of Object.entries(visuals)) {
  L.push(`        [${csStr(name)}] = new(MoveFxPattern.${v.pattern}, ${csStr(v.sprite)}),`);
}
L.push('    };');
L.push('');
L.push('    private static readonly MoveVisual Fallback = new(MoveFxPattern.Projectile, "wisp");');
L.push('');
L.push('    public static MoveVisual For(string moveName) =>');
L.push('        ByName.TryGetValue(moveName, out var visual) ? visual : Fallback;');
L.push('}');

fs.writeFileSync(path.join(__dirname, 'out', 'MoveVisuals.g.cs'), L.join('\n') + '\n');
console.log('MoveVisuals.g.cs:', Object.keys(visuals).length, 'entries');
